### ISSUE TITLE
Atividade Integradora - Prática 1º Bimestre

### ISSUE THREAD

**Issue by prof-rafael** [prof-rafael/Oficinas-de-Programacao#2]
Posta nessa Issue a Atividade Integradora.
Dê um git push de sua atividade no seu repositório, poste aqui o Link da sua commit "Hash of revision"

**Comment by joaovs** [comment]
[Atividade Integradora.pdf](https://github.com/prof-rafael/Oficinas-de-Programacao/files/1934010/Atividade.Integradora.pdf)

Do aluno João Vitor Salvadori

**Comment by faneco** [comment]
[Atividade](https://github.com/faneco/Oficinas-de-Programacao/blob/master/Atividade%20Integradora.txt)

Nome: Douglas Faneco de Lima
Ra:13456.15

**Comment by gustavolev** [comment]
Atividade integradora: [Regex](https://github.com/prof-rafael/Oficinas-de-Programacao/files/1934544/Regex.pdf)

Nome: Gustavo Bueno Levorato
Ra: 13396.15

**Comment by marcelovieira1** [comment]
Atividade integradora MArcelo Vieira
RA: 13706.15

https://github.com/marcelovieira1/oficina/blob/master/atividadeintegradora2.txt

**Comment by alissoneric** [comment]
[Atividade integradora](https://github.com/alissondex/oficina2018/blob/ffa01d60df35c19dc6e50243844b78fa734f543a/integradora.pdf)

Alisson Eric
13616.15

**Comment by fgiarol** [comment]
[Expressoesregulares.pdf](https://github.com/prof-rafael/Oficinas-de-Programacao/files/1934659/Expressoesregulares.pdf)

Pesquisa sobre Expressões Regulares em Linux

Aluno: Fernando Rodrigues Giarola
R.A: 13806.15
