### ISSUE TITLE
Atividade Prática - Shell Script

### ISSUE THREAD

**Issue by prof-rafael** [prof-rafael/Oficinas-de-Programacao#3]
Poste nessa Issue...

**Comment by joaovs** [comment]
https://github.com/joaovs/Oficina-de-Programacao/blob/a908411cac2456c469f3787eb9c23452d95dd9ad/Exercicio9.sh

Aluno: João Vitor Salvadori
R.A.: 13810.15

**Comment by alissondex** [comment]
```bash
#!/bin/bash

ARQUIVO="NmapScan-sP.txt"
RELATORIO="Relatorio.txt"
DATA=$(date)

nmap -sP 192.168.9.70/24 > $ARQUIVO

cat $ARQUIVO | grep "Nmap scan" | cut -d " " -f5 > IP.txt
cat $ARQUIVO | grep "MAC" | cut -d " " -f3 > MAC.txt

echo "*****************************************" >> $RELATORIO
echo "*              RELATORIO                *" >> $RELATORIO
echo "*****************************************" >> $RELATORIO
echo "Alisson Eric Silva Ferreira de Souza" >> $RELATORIO
echo "" >> $RELATORIO
echo "Data: $DATA" >> $RELATORIO
echo "" >> $RELATORIO

LINES=$(wc -l IP.txt | cut -d " " -f1)
for i in $(seq "1" "$LINES")
do
	IP_ATUAL=$(head -n${i} IP.txt | tail -1)
	MAC_ATUAL=$(head -n${i} MAC.txt | tail -1)
	echo "$IP_ATUAL" >> $RELATORIO
	echo "$MAC_ATUAL" >> $RELATORIO
	echo "" >> $RELATORIO
	
done

cat $RELATORIO | ssmtp raffael.rbarbosa@gmail.com
```

**Comment by alissoneric** [comment]
Veja [aqui](https://github.com/alissondex/oficina2018/blob/5f14ef2ba08b2522ab7a15fb7dd77754ac16452c/trabalho_1b.sh) o código do trabalho

Aluno: Alisson Eric Silva Ferreira de Souza
R.A.: 13616.15

**Comment by marcelovieira1** [comment]
https://github.com/marcelovieira1/oficina/commit/3fbc80aa839735a057886d5e521c8ade2c3f3517

Aluno: Marcelo Vieira
RA: 13706.15

**Comment by fgiarol** [comment]
[Trabalho Prático](https://github.com/Fernandogr10/nhoque/blob/master/ipmac.txt)

Aluno: Fernando Rodrigues Giarola
R.A: 13806.15
\o/

**Comment by gustavolev** [comment]
Link do trabalho: [trab](https://github.com/iGustL/OficinaProgramacao/blob/master/ips.sh)

Aluno: Gustavo Bueno Levorato
RA: 13396.15

**Comment by NortonWaki** [comment]
[Trabalho pratico - Norton](https://github.com/NortonWaki/Oficina-de-programacao/blob/master/atividadeIntegradora.sh)

Aluno: Norton Noboru Waki
R.A: 13696.15

**Comment by faneco** [comment]
[Trabalho](https://github.com/faneco/Oficinas-de-Programacao/blob/master/trabalho.sh)


Nome: Douglas Faneco de Lima
Ra: 13456.15
